//
// Created by maxim on 2/23/19.
//

#ifndef ZOMBOID2_MESSAGETYPES_H
#define ZOMBOID2_MESSAGETYPES_H

#define MSGTYPE__CONNECTED -2
#define MSGTYPE__ANY -1

#define MSGTYPE_INIT_RES 0
#define MSGTYPE_INIT_REQ 1

#endif //ZOMBOID2_MESSAGETYPES_H
